import type { EnglishQuestion } from './english-data'

export const ASSESSMENT_QUESTION_BANK: EnglishQuestion[] = [
  { id: 'r1', type: 'choice', skill: 'recognition', difficulty: 1, prompt: 'quiet 最接近哪個意思？', answer: '安靜的', choices: ['安靜的', '昂貴的', '遙遠的', '危險的'], explanation: 'quiet 表示安靜、沒有太多聲音。' },
  { id: 'r2', type: 'choice', skill: 'recognition', difficulty: 1.5, prompt: 'borrow 最接近哪個意思？', answer: '借入', choices: ['歸還', '借入', '販售', '修理'], explanation: 'borrow 是向別人借入；lend 是借給別人。' },
  { id: 'r3', type: 'choice', skill: 'recognition', difficulty: 2, prompt: 'available 最接近哪個意思？', answer: '可用的；有空的', choices: ['可用的；有空的', '昂貴的', '危險的', '狹窄的'], explanation: 'available 可表示某物可取得、可使用，或某人有空。' },
  { id: 'r4', type: 'choice', skill: 'recognition', difficulty: 2.5, prompt: 'reliable 最接近哪個意思？', answer: '可靠的', choices: ['可靠的', '暫時的', '害羞的', '傳統的'], explanation: 'reliable 表示值得信賴、能穩定完成事情。' },
  { id: 'r5', type: 'choice', skill: 'recognition', difficulty: 3, prompt: 'efficient 最接近哪個意思？', answer: '有效率的', choices: ['有效率的', '有耐心的', '有禮貌的', '有創意的'], explanation: 'efficient 指以較少時間或資源完成工作。' },
  { id: 'r6', type: 'choice', skill: 'recognition', difficulty: 3.5, prompt: 'maintain 最接近哪個意思？', answer: '維持；保養', choices: ['避免', '維持；保養', '比較', '承認'], explanation: 'maintain 可表示維持狀態或保養設備。' },
  { id: 'r7', type: 'choice', skill: 'recognition', difficulty: 4, prompt: 'significant 最接近哪個意思？', answer: '重要的；顯著的', choices: ['重要的；顯著的', '普通的', '可疑的', '可移動的'], explanation: 'significant 表示影響大、值得注意。' },
  { id: 'r8', type: 'choice', skill: 'recognition', difficulty: 4.5, prompt: 'comprehensive 最接近哪個意思？', answer: '全面而完整的', choices: ['容易理解的', '全面而完整的', '不相關的', '暫時性的'], explanation: 'comprehensive 表示涵蓋大部分內容與細節。' },
  { id: 'r9', type: 'choice', skill: 'recognition', difficulty: 5, prompt: 'inevitable 最接近哪個意思？', answer: '不可避免的', choices: ['無法預測的', '不可避免的', '值得懷疑的', '可以逆轉的'], explanation: 'inevitable 表示一定會發生、無法避免。' },
  { id: 'r10', type: 'choice', skill: 'recognition', difficulty: 5.5, prompt: 'meticulous 最接近哪個意思？', answer: '一絲不苟的', choices: ['一絲不苟的', '容易滿足的', '反覆無常的', '缺乏經驗的'], explanation: 'meticulous 表示非常仔細並注意每個細節。' },

  { id: 's1', type: 'typing', skill: 'spelling', difficulty: 1, prompt: '請輸入「朋友」的英文。', answer: 'friend', explanation: 'friend 的字母順序是 f-r-i-e-n-d。' },
  { id: 's2', type: 'typing', skill: 'spelling', difficulty: 1.5, prompt: '請輸入「因為」的英文。', answer: 'because', explanation: 'because 是常見連接詞，表示原因。' },
  { id: 's3', type: 'typing', skill: 'spelling', difficulty: 2, prompt: '請輸入「環境」的英文。', answer: 'environment', explanation: 'environment 中間是 environ + ment，注意不要漏掉 n。' },
  { id: 's4', type: 'typing', skill: 'spelling', difficulty: 2.5, prompt: '請輸入「負責任的」英文。', answer: 'responsible', explanation: 'responsible 常搭配 be responsible for。' },
  { id: 's5', type: 'typing', skill: 'spelling', difficulty: 3, prompt: '請輸入「維持；保養」的英文動詞。', answer: 'maintain', explanation: 'maintain 可表示維持狀態或保養設備。' },
  { id: 's6', type: 'typing', skill: 'spelling', difficulty: 3.5, prompt: '請輸入「有效率的」英文。', answer: 'efficient', explanation: 'efficient 的中段是 -fici-，不要和 effective 混淆。' },
  { id: 's7', type: 'typing', skill: 'spelling', difficulty: 4, prompt: '請輸入「實施；執行」的英文動詞。', answer: 'implement', explanation: 'implement a plan 表示執行一項計畫。' },
  { id: 's8', type: 'typing', skill: 'spelling', difficulty: 4.5, prompt: '請輸入「全面的；綜合的」英文。', answer: 'comprehensive', explanation: 'comprehensive 常搭配 report、review、solution。' },
  { id: 's9', type: 'typing', skill: 'spelling', difficulty: 5, prompt: '請輸入「不可避免的」英文。', answer: 'inevitable', explanation: 'in-（不）＋ evit（避免）＋ -able（能夠……的）。' },
  { id: 's10', type: 'typing', skill: 'spelling', difficulty: 5.5, prompt: '請輸入「一絲不苟的」英文。', answer: 'meticulous', explanation: 'meticulous 表示對細節非常仔細。' },

  { id: 'g1', type: 'cloze', skill: 'grammar', difficulty: 1, prompt: 'I _____ a student.', answer: 'am', context: '請填入正確的 be 動詞。', explanation: '主詞 I 搭配 am。' },
  { id: 'g2', type: 'correction', skill: 'grammar', difficulty: 1.5, prompt: '請改正句子：He have a car.', answer: 'he has a car', explanation: '第三人稱單數 he 搭配 has。' },
  { id: 'g3', type: 'cloze', skill: 'grammar', difficulty: 2, prompt: 'The service is _____ twenty-four hours a day.', answer: 'available', context: '請輸入最自然的單字。', explanation: 'be available 表示可以使用或可以聯絡。' },
  { id: 'g4', type: 'correction', skill: 'grammar', difficulty: 2.5, prompt: '請改正句子：She go to work every day.', answer: 'she goes to work every day', explanation: '第三人稱單數 she 的一般現在式動詞需加 -s：goes。' },
  { id: 'g5', type: 'cloze', skill: 'grammar', difficulty: 3, prompt: 'We have lived here _____ 2022.', answer: 'since', explanation: 'since 後面接明確起始時間；for 後面接一段時間。' },
  { id: 'g6', type: 'correction', skill: 'grammar', difficulty: 3.5, prompt: '請改正句子：I have finished the task yesterday.', answer: 'i finished the task yesterday', explanation: 'yesterday 是明確過去時間，通常使用過去式 finished。' },
  { id: 'g7', type: 'cloze', skill: 'grammar', difficulty: 4, prompt: 'The team will _____ the new feature next week.', answer: 'implement', context: '意思是「實施新功能」。', explanation: 'implement a feature 表示把功能真正投入運作。' },
  { id: 'g8', type: 'correction', skill: 'grammar', difficulty: 4.5, prompt: '請改正句子：The information are not complete.', answer: 'the information is not complete', explanation: 'information 是不可數名詞，在此搭配單數動詞 is。' },
  { id: 'g9', type: 'cloze', skill: 'grammar', difficulty: 5, prompt: 'Had I known about the delay, I _____ earlier.', answer: 'would have left', explanation: '這是與過去事實相反的第三類條件句。' },
  { id: 'g10', type: 'correction', skill: 'grammar', difficulty: 5.5, prompt: '請改正句子：Neither of the answers are correct.', answer: 'neither of the answers is correct', explanation: 'neither 在正式用法中通常視為單數，搭配 is。' },

  { id: 'rd1', type: 'choice', skill: 'reading', difficulty: 1, prompt: '“Tom is tired, so he goes to bed early.” Tom 為什麼早睡？', answer: '因為他累了', choices: ['因為他累了', '因為他餓了', '因為他遲到了', '因為他生病了'], explanation: '句中的 so 表示前面的 tired 是早睡原因。' },
  { id: 'rd2', type: 'choice', skill: 'reading', difficulty: 1.5, prompt: '“The shop closes at six.” 商店何時關門？', answer: '六點', choices: ['五點', '六點', '七點', '八點'], explanation: '句子直接說 closes at six。' },
  { id: 'rd3', type: 'choice', skill: 'reading', difficulty: 2, prompt: '“Mia missed the bus, but she arrived on time by taxi.” 哪個敘述正確？', answer: '她搭計程車準時抵達', choices: ['她沒有出門', '她搭計程車準時抵達', '她搭公車遲到', '她取消行程'], explanation: '雖然錯過公車，她仍搭計程車準時抵達。' },
  { id: 'rd4', type: 'choice', skill: 'reading', difficulty: 2.5, prompt: '“The update made the process faster and reduced wasted steps.” 最接近哪個形容詞？', answer: 'efficient', choices: ['efficient', 'ancient', 'nervous', 'temporary'], explanation: '減少浪費並提升速度，表示流程更 efficient。' },
  { id: 'rd5', type: 'choice', skill: 'reading', difficulty: 3, prompt: '“Please submit the form by Friday. Late forms will not be accepted.” 最重要的要求是什麼？', answer: '星期五前繳交', choices: ['星期五前繳交', '只需口頭通知', '下週再填', '不需要簽名'], explanation: 'by Friday 表示最晚要在星期五前完成。' },
  { id: 'rd6', type: 'choice', skill: 'reading', difficulty: 3.5, prompt: '“The server is running, but users still cannot log in.” 可以推論什麼？', answer: '服務啟動不代表登入功能正常', choices: ['伺服器一定關機', '服務啟動不代表登入功能正常', '所有帳號都被刪除', '網路一定中斷'], explanation: '句子指出伺服器運作中，但登入仍有問題。' },
  { id: 'rd7', type: 'choice', skill: 'reading', difficulty: 4, prompt: '“The policy was introduced to reduce unnecessary spending without affecting essential services.” 政策目標是什麼？', answer: '減少非必要支出並保留必要服務', choices: ['停止所有服務', '增加所有支出', '減少非必要支出並保留必要服務', '取消預算管理'], explanation: 'without affecting essential services 表示必要服務仍需保留。' },
  { id: 'rd8', type: 'choice', skill: 'reading', difficulty: 4.5, prompt: '“Although the proposal is comprehensive, its cost may prevent immediate implementation.” 主要顧慮是什麼？', answer: '成本可能使計畫無法立即實施', choices: ['內容不完整', '成本可能使計畫無法立即實施', '缺少任何目標', '計畫已經完成'], explanation: 'although 後面轉折指出 cost 是立即實施的阻礙。' },
  { id: 'rd9', type: 'choice', skill: 'reading', difficulty: 5, prompt: '“Her report checked every tiny detail and contained no careless errors.” 最符合哪個字？', answer: 'meticulous', choices: ['inevitable', 'meticulous', 'available', 'casual'], explanation: '仔細檢查每個細節可用 meticulous 描述。' },
  { id: 'rd10', type: 'choice', skill: 'reading', difficulty: 5.5, prompt: '“The findings are preliminary and should not be treated as conclusive evidence.” 作者提醒讀者什麼？', answer: '目前結果還不能視為最終證據', choices: ['研究已完全證實', '目前結果還不能視為最終證據', '資料沒有任何價值', '研究不需再進行'], explanation: 'preliminary 與 not conclusive 表示結果仍屬初步。' },

  { id: 'l1', type: 'listening', skill: 'listening', difficulty: 1, prompt: '播放後，輸入你聽到的單字。', answer: 'morning', audioText: 'morning', explanation: 'morning 表示早晨。' },
  { id: 'l2', type: 'listening', skill: 'listening', difficulty: 1.5, prompt: '播放後，輸入你聽到的單字。', answer: 'because', audioText: 'because', explanation: 'because 用來說明原因。' },
  { id: 'l3', type: 'listening', skill: 'listening', difficulty: 2, prompt: '播放後，輸入你聽到的單字。', answer: 'responsible', audioText: 'responsible', explanation: 'responsible 表示負責任的。' },
  { id: 'l4', type: 'listening', skill: 'listening', difficulty: 2.5, prompt: '播放後，輸入你聽到的片語。', answer: 'available now', audioText: 'available now', explanation: 'available now 表示目前可用或現在有空。' },
  { id: 'l5', type: 'listening', skill: 'listening', difficulty: 3, prompt: '播放後，輸入你聽到的單字。', answer: 'significant', audioText: 'significant', explanation: 'significant 表示重要的或顯著的。' },
  { id: 'l6', type: 'listening', skill: 'listening', difficulty: 3.5, prompt: '播放後，輸入你聽到的片語。', answer: 'maintain quality', audioText: 'maintain quality', explanation: 'maintain quality 表示維持品質。' },
  { id: 'l7', type: 'listening', skill: 'listening', difficulty: 4, prompt: '播放後，輸入你聽到的單字。', answer: 'implement', audioText: 'implement', explanation: 'implement 表示實施或執行。' },
  { id: 'l8', type: 'listening', skill: 'listening', difficulty: 4.5, prompt: '播放後，輸入你聽到的片語。', answer: 'comprehensive review', audioText: 'comprehensive review', explanation: 'comprehensive review 表示全面的檢視。' },
  { id: 'l9', type: 'listening', skill: 'listening', difficulty: 5, prompt: '播放後，輸入你聽到的單字。', answer: 'meticulous', audioText: 'meticulous', explanation: 'meticulous 表示一絲不苟的。' },
  { id: 'l10', type: 'listening', skill: 'listening', difficulty: 5.5, prompt: '播放後，輸入你聽到的片語。', answer: 'inevitable consequence', audioText: 'inevitable consequence', explanation: 'inevitable consequence 表示不可避免的後果。' },
]
